dist: trusty
language: java
jdk:
 - oraclejdk13

addons:
 sonarcloud:
  organization: "progettoispw2019"
  token:
   secure: 8863f88d700d966cc8496b48d771497d3001293a

script: 
- ant build
- sonar-scanner
