dist: trusty
language: java
jdk:
 - oraclejdk13

addons:
 sonarcloud:
  organization: "progettoispw2019"
  token:
   secure: "59ba73dfac00f78b7af5d15311ebd38794e0dcb5"

script: 
- ant build
- sonar-scanner
